lib/excommerce_web/router.ex
defmodule ExcommerceWeb.Router do
  use ExcommerceWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Phauxth.Authenticate
    plug Phauxth.Remember
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ExcommerceWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    resources "/products", ProductController, only: [:show, :index]

    resources "/categories", CategoryController do
      get "/products", CategoryController, :associated_products, as: :products
    end

    resources "/users", UserController
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    get "/confirm", ConfirmController, :index
    resources "/password_resets", PasswordResetController, only: [:new, :create]
    get "/password_resets/edit", PasswordResetController, :edit
    put "/password_resets/update", PasswordResetController, :update
  end

  scope "/admin", ExcommerceWeb.Admin, as: :admin do
    pipe_through :browser

    get "/", HomeController, :index

    resources "/products", ProductController do
      resources "/variants", VariantController
    end

    resources "/countries", CountryController do
      resources "/states", StateController, only: [:create, :delete]
    end
    resources "/zones", ZoneController do
      resources "/members", ZoneMemberController, only: [:create, :delete]
    end

    resources "/cart", CartController, only: [:new, :edit, :create]

    resources "/categories", CategoryController
    resources "/themes", ThemeController, except: [:edit, :update, :new, :create]
    resources "/option_types", OptionTypeController, except: [:show]

    resources "/orders", OrderController, only: [:index, :show, :update, :edit] do
      resources "/line_items", LineItemController, only: [:create, :delete] do
        put "/update_fullfillment", LineItemController, :update_fullfillment
      end
      get "/checkout", CheckoutController, :checkout
      put "/checkout/next", CheckoutController, :next
      put "/checkout/back", CheckoutController, :back
      resources "/payments", PaymentController, only: [:show] do
        put "/refund",  PaymentController, :refund,  as: :refund
        put "/capture", PaymentController, :capture, as: :capture
      end
    end

    resources "/users", UserController do
      get "/all_pending_orders", UserController, :all_pending_orders
    end

    resources "/users", UserController

    get "/settings", SettingsController, :show
    put "/settings", SettingsController, :update
    put "/settings/theme", SettingsController, :update_theme
    get "/settings/payment", SettingsController,  :payment_method_settings
    get "/settings/shipping", SettingsController, :shipping_method_settings
    post "/settings/payment", SettingsController,  :update_payment_method_settings
    post "/settings/shipping", SettingsController, :update_shipping_method_settings
  end

  # Other scopes may use custom stacks.
  # scope "/api", ExcommerceWeb do
  #   pipe_through :api
  # end
end

lib/excommerce_web/templates/page/index.html.eex
<!-- banner section -->
<div class="xs-banner">
    <div class="xs-banner-slider owl-carousel">
        <%= for product <- @products do %>
        <div class="xs-banner-item" style="background-image:url('<%= static_path(@conn, "/images/front/slider_bg_1.jpg") %>')">
          <div class="container">
              <div class="row">
                  <div class="col-md-5 xs-banner-image animInLeft">
                      <img src="<%= ExcommerceWeb.VariantImage.url({product.master.image, product.master}) %>" alt="">
                  </div>
                  <div class="col-md-6 xs-banner-content">
                      <h2 class="xs-banner-sub-title animInTop"><%= product.ante_title %></h2>
                      <h3 class="xs-banner-title animInBottom"><%= product.name %></h3>
                      <p><%= raw product.short_description %></p>
                      <div class="xs-btn-wraper">
                          <a href="<%= product_path(@conn, :show, product) %>" class="btn btn-outline-primary animInLeft">LEARN MORE</a>
                          <a href="#" class="btn btn-primary animInRight">SHOP COLLECTION</a>
                      </div>
                  </div>

              </div>
          </div>
        </div>
        <% end %>
    </div>
</div>

<!-- feature product section -->
<div class="xs-section-padding xs-feauture-product-section">
    <div class="container">
        <div class="xs-heading">
            <h2 class="xs-heading-sub">Planet Security Collections</h2>
            <h3 class="xs-heading-title">Featured Products</h3>
        </div>
        <div class="row">
            <div class="col-lg-6">
              <%= for {product, index} <- Enum.with_index(@products) do %>
              <%= if index == 0 do %>
                <div class="xs-feature-product highlight">
                    <%= if product.master.image do %>
                    <img src="<%= static_path(@conn, "/images/front/image_loader.gif") %>" data-echo="<%= ExcommerceWeb.VariantImage.url({product.master.image, product.master}) %>" class="image_featured" alt="">
                    <% end %>
                    <div class="xs-feature-product-info">
                        <h4 class="product-title-v2 large"><a href="<%= product_path(@conn, :show, product) %>"><%= product.ante_title %><strong><%= product.name %></strong></a></h4>
                        <a href="#" class="btn btn-primary">VIEW COLLECTION</a>
                    </div>
                    <div class="xs-product-offer-label">
                        <span>$<%= product.master.cost_price %></span>
                        <small>Offer</small>
                    </div>
                </div>
              <% end %>
              <% end %>
            </div>
            <div class="col-lg-6 xs-padding-0">
                <div class="row xs-margin-0">
                    <%= for {product, index} <- Enum.with_index(@products) do %>
                    <%= if index != 0 do %>
                    <div class="col-md-6">
                        <div class="xs-feature-product">
                            <%= if product.master.image do %>
                            <img src="<%= static_path(@conn, "/images/front/image_loader.gif") %>" data-echo="<%= ExcommerceWeb.VariantImage.url({product.master.image, product.master}) %>" class="image_t" alt="">
                            <% end %>
                            <div class="xs-feature-product-info">
                                <h4 class="product-title-v2"><a href="<%= product_path(@conn, :show, product) %>"><%= product.ante_title %><strong><%= product.name %></strong></a></h4>
                            </div>
                        </div>
                    </div>
                    <% end %>
                    <% end %>
                </div>
            </div>
        </div>


    </div>
</div>