lib/excommerce_web/router.ex
defmodule ExcommerceWeb.Router do
  use ExcommerceWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Phauxth.Authenticate
    plug Phauxth.Remember
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ExcommerceWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    resources "/products", ProductController, only: [:show, :index]

    resources "/categories", CategoryController do
      get "/products", CategoryController, :associated_products, as: :products
    end

    resources "/users", UserController
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    get "/confirm", ConfirmController, :index
    resources "/password_resets", PasswordResetController, only: [:new, :create]
    get "/password_resets/edit", PasswordResetController, :edit
    put "/password_resets/update", PasswordResetController, :update
  end

  scope "/admin", ExcommerceWeb.Admin, as: :admin do
    pipe_through :browser

    get "/", HomeController, :index

    resources "/products", ProductController do
      resources "/variants", VariantController
    end

    resources "/countries", CountryController do
      resources "/states", StateController, only: [:create, :delete]
    end
    resources "/zones", ZoneController do
      resources "/members", ZoneMemberController, only: [:create, :delete]
    end

    resources "/cart", CartController, only: [:new, :edit, :create]

    resources "/categories", CategoryController
    resources "/themes", ThemeController, except: [:edit, :update, :new, :create]
    resources "/option_types", OptionTypeController, except: [:show]

    resources "/orders", OrderController, only: [:index, :show, :update, :edit] do
      resources "/line_items", LineItemController, only: [:create, :delete] do
        put "/update_fullfillment", LineItemController, :update_fullfillment
      end
      get "/checkout", CheckoutController, :checkout
      put "/checkout/next", CheckoutController, :next
      put "/checkout/back", CheckoutController, :back
      resources "/payments", PaymentController, only: [:show] do
        put "/refund",  PaymentController, :refund,  as: :refund
        put "/capture", PaymentController, :capture, as: :capture
      end
    end

    resources "/users", UserController do
      get "/all_pending_orders", UserController, :all_pending_orders
    end

    resources "/users", UserController

    get "/settings", SettingsController, :show
    put "/settings", SettingsController, :update
    put "/settings/theme", SettingsController, :update_theme
    get "/settings/payment", SettingsController,  :payment_method_settings
    get "/settings/shipping", SettingsController, :shipping_method_settings
    post "/settings/payment", SettingsController,  :update_payment_method_settings
    post "/settings/shipping", SettingsController, :update_shipping_method_settings
  end

  # Other scopes may use custom stacks.
  # scope "/api", ExcommerceWeb do
  #   pipe_through :api
  # end
end

lib/excommerce_web/views/front_view.ex
defmodule ExcommerceWeb.FrontView do
  use ExcommerceWeb, :view
end

lib/excommerce_web/templates/front/_footer.html.eex
<!-- footer section start -->
<footer class="xs-footer-section">
    <div class="xs-footer-main">
        <div class="container">
            <div class="xs-footer-logo">
                <a href="<%= page_path(@conn, :index) %>">
                    <img src="<%= static_path(@conn, "/images/front/footer_logo.png") %>" alt="">
                </a>
            </div><!-- .xs-footer-logo END -->
            <div class="row">
                <div class="col-md-6 col-lg-5 footer-widget footer-content">
                    <h3 class="widget-title">MarketPress Super Points™ Program</h3>
                    <div class="media xs-footer-description">
                        <img src="<%= static_path(@conn, "/images/front/points.png") %>" alt="Generic placeholder image">
                        <div class="media-body align-self-center">
                            <p>Earn reward points every time you shop on marketpress.com. Not a member yet? <a href="#">Join for Free</a></p>
                        </div>
                    </div><!-- .media .xs-footer-description END -->
                    <h3 class="widget-title">Available Now</h3>
                    <div class="xs-btn-wraper">
                        <a href="#">
                            <img src="<%= static_path(@conn, "/images/front/play-store.png") %>" alt="">
                        </a>
                        <a href="#">
                            <img src="<%= static_path(@conn, "/images/front/app-store.png") %>" alt="">
                        </a>
                    </div><!-- .xs-btn-wraper END -->
                </div><!-- .footer-widget .footer-content END -->
                <div class="col-md-6 col-lg-2 footer-widget">
                    <h3 class="widget-title">Quick Links</h3>
                    <ul class="xs-list">
                        <li><a href="#">Support Center</a>							</li>
                        <li><a href="#">Term & Conditions</a></li>
                        <li><a href="#">Shipping</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                        <li><a href="#">Help</a></li>
                        <li><a href="#">Products Return</a></li>
                        <li><a href="#">FAQS</a></li>
                    </ul><!-- .xs-list END -->
                </div><!-- .footer-widget END -->
                <div class="col-md-6 col-lg-2 footer-widget">
                    <h3 class="widget-title">Our Stores</h3>
                    <ul class="xs-list">
                        <li><a href="#">New York</a></li>
                        <li><a href="#">London SF</a></li>
                        <li><a href="#">Cockfosters BP</a></li>
                        <li><a href="#">Los Angeles</a></li>
                        <li><a href="#">Chicago</a></li>
                        <li><a href="#">Las Vegas</a></li>
                        <li><a href="#">Albarto</a></li>
                    </ul><!-- .xs-list END -->
                </div><!-- .footer-widget END -->
                <div class="col-md-6 col-lg-3 footer-widget">
                    <h3 class="widget-title">News Feeds</h3>
                    <div class="xs-tweet"></div>
                </div><!-- .footer-widget END -->
            </div>
        </div>
    </div><!-- .xs-footer-main END -->
    <div class="xs-copyright">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="xs-copyright-text">
                        &copy; 2018 <a href="https://themeforest.net/user/xpeedstudio/portfolio">XpeedStudio</a> All Rights Reserved
                    </div><!-- .xs-copyright-text END -->
                </div>

            </div>
        </div>
    </div><!-- .xs-copyright END -->
</footer>
<!-- footer section end -->

lib/excommerce_web/templates/front/_header.html.eex
<header class="xs-header">
    <!-- nav bar section -->
    <div class="xs-navBar">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-sm-4 xs-order-1">
                    <div class="xs-logo-wraper">
                        <a href="<%= page_path(@conn, :index) %>">
                            <img src="<%= static_path(@conn, "/images/front/logo.png") %>" alt="">
                        </a>
                    </div>
                </div>

                <div class="col-lg-7 col-sm-3 xs-order-3 xs-menus-group">
                    <nav class="xs-menus">
                        <div class="nav-header">
                            <div class="nav-toggle"></div>
                        </div><!-- .nav-header END -->
                        <div class="nav-menus-wrapper">
                            <ul class="nav-menu">
                                <li class="active"><a href="<%= page_path(@conn, :index) %>">Home</a></li>
                                <li class=""><a href="<%= page_path(@conn, :index) %>"><span class="menu-label">NEW</span>Shop</a></li>
                                <li class=""><a href="<%= page_path(@conn, :index) %>">Blog</a></li>
                                <li class=""><a href="<%= page_path(@conn, :index) %>"><span class="menu-label highlight">HOT</span>Gallery</a></li>
                            </ul>
                        </div>
                    </nav>
                </div>
                <div class="col-lg-2 col-sm-5 xs-order-2 xs-wishlist-group">
                    <div class="xs-wish-list-item">
                    <span class="xs-wish-list">
                        <a href="#" class="xs-single-wishList d-none d-md-none d-lg-block">
                            <span class="xs-item-count">0</span>
                            <i class="icon icon-heart"></i>
                        </a>
                    </span>
                        <span class="xs-wish-list">
                        <a href="" class="xs-single-wishList d-none d-md-none d-lg-block">
                            <span class="xs-item-count">0</span>
                            <i class="icon icon-arrows"></i>
                        </a>
                    </span>
                        <div class="xs-miniCart-dropdown">
                            <a href="#" class="xs-single-wishList offset-cart-menu">
                                <span class="xs-item-count highlight">3</span>
                                <i class="icon icon-bag"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div><!-- .row END -->
        </div><!-- .container END -->
    </div>    <!-- End nav bar section -->

    <!-- sidebar cart item -->


    <!-- nav down section -->
    <div class="xs-navDown">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 d-none d-md-none d-lg-block">
                    <!-- vertical menu bar -->
                    <div class="cd-dropdown-wrapper xs-vartical-menu">
                        <a class="cd-dropdown-trigger" href="#0">
                            <i class="fa fa-list-ul"></i> All Categories
                        </a>

                        <nav class="cd-dropdown">
                            <h2>Planet Security</h2>
                            <a href="#0" class="cd-close">Close</a>
                            <ul class="cd-dropdown-content">
                                <%= for mcat <- @root_cat do %>
                                <li class="">
                                    <a class="no-padding" href="<%= category_products_path(@conn, :associated_products, mcat) %>"><i class="icon icon-<%= mcat.icon %>"></i><%= mcat.name %> </i></a>

                                </li>
                                <% end %>
                            </ul>
                        </nav>

                    </div> <!-- .cd-dropdown-wrapper -->
                    <!-- End vertical menu bar -->
                </div>
                <div class="col-lg-6">
                    <form class="xs-navbar-search" method="get" action="#">
                        <div class="input-group">
                            <input type="search" class="form-control" placeholder="Find your product">
                            <div class="xs-category-select-wraper">
                                <select class="xs-category-select">
                                    <option value="0">All Categories</option>

                                </select>
                            </div>
                            <div class="input-group-btn">
                                <input type="hidden" id="search-param" name="post_type" value="product">
                                <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-lg-3 d-none d-md-none d-lg-block">
                    <div style="color: #0063d1;font-size: 1.3em;"><strong>(305) 455-1722</strong></div>
                    <div style="color: #0063d1;font-size: 1.0em;"><strong>Sales & Solutions</strong></div>
                    <span style="color: red;font-size: 0.8em">Hablamos español/</span>
                    <span style="color: #83b735;font-size: 0.8em">Falamos portugues</span>
                </div>
            </div><!-- .row END -->
        </div><!-- .container END -->
    </div>    <!-- End nav down section -->

    <!-- <div class="nav-cover"></div> -->
</header>
<!-- End header section -->

lib/excommerce_web/templates/front/_top_bar.html.eex
<div class="xs-top-bar d-none d-md-none d-lg-block">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="xs-top-bar-info">
                                <li><a href="#"><i class="icon icon-van "></i>Free Delivery</a></li>
                                <li><a href="#">Return Policy</a></li>
                            </ul><!-- .xs-top-bar-info END -->
                        </div>
                        <div class="col-lg-6">
                            <ul class="xs-social-list">
                                <li class="xs-list-text">Follow Us</li>
                                <li><a href="#"><i class="icon icon-facebook"></i></a></li>
                                <li><a href="#"><i class="icon icon-twitter"></i></a></li>
                                <li><a href="#"><i class="icon icon-pinterest"></i></a></li>
                                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                            </ul><!-- .xs-social-list END -->
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <ul class="xs-top-bar-info right-content">
                        <li><a href="<%= page_path(@conn, :index) %>" style="color: #0063d1">ENG</a> </li>
                        <li><a href="<%= session_path(@conn, :new) %>" >Login</a></li>
                    </ul>
                </div>
            </div><!-- .row END -->
        </div><!-- .container END -->
</div>