lib/excommerce_web/router.ex
defmodule ExcommerceWeb.Router do
  use ExcommerceWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Phauxth.Authenticate
    plug Phauxth.Remember
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ExcommerceWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    resources "/products", ProductController, only: [:show, :index]

    resources "/categories", CategoryController do
      get "/products", CategoryController, :associated_products, as: :products
    end

    resources "/users", UserController
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    get "/confirm", ConfirmController, :index
    resources "/password_resets", PasswordResetController, only: [:new, :create]
    get "/password_resets/edit", PasswordResetController, :edit
    put "/password_resets/update", PasswordResetController, :update
  end

  scope "/admin", ExcommerceWeb.Admin, as: :admin do
    pipe_through :browser

    get "/", HomeController, :index

    resources "/products", ProductController do
      resources "/variants", VariantController
    end

    resources "/countries", CountryController do
      resources "/states", StateController, only: [:create, :delete]
    end
    resources "/zones", ZoneController do
      resources "/members", ZoneMemberController, only: [:create, :delete]
    end

    resources "/cart", CartController, only: [:new, :edit, :create]

    resources "/categories", CategoryController
    resources "/themes", ThemeController, except: [:edit, :update, :new, :create]
    resources "/option_types", OptionTypeController, except: [:show]

    resources "/orders", OrderController, only: [:index, :show, :update, :edit] do
      resources "/line_items", LineItemController, only: [:create, :delete] do
        put "/update_fullfillment", LineItemController, :update_fullfillment
      end
      get "/checkout", CheckoutController, :checkout
      put "/checkout/next", CheckoutController, :next
      put "/checkout/back", CheckoutController, :back
      resources "/payments", PaymentController, only: [:show] do
        put "/refund",  PaymentController, :refund,  as: :refund
        put "/capture", PaymentController, :capture, as: :capture
      end
    end

    resources "/users", UserController do
      get "/all_pending_orders", UserController, :all_pending_orders
    end

    resources "/users", UserController

    get "/settings", SettingsController, :show
    put "/settings", SettingsController, :update
    put "/settings/theme", SettingsController, :update_theme
    get "/settings/payment", SettingsController,  :payment_method_settings
    get "/settings/shipping", SettingsController, :shipping_method_settings
    post "/settings/payment", SettingsController,  :update_payment_method_settings
    post "/settings/shipping", SettingsController, :update_shipping_method_settings
  end

  # Other scopes may use custom stacks.
  # scope "/api", ExcommerceWeb do
  #   pipe_through :api
  # end
end

lib/excommerce_web/controllers/session_controller.ex
defmodule ExcommerceWeb.SessionController do
  use ExcommerceWeb, :controller

  import ExcommerceWeb.Authorize
  alias Excommerce.Accounts
  alias Phauxth.Confirm.Login

  plug :guest_check when action in [:new, :create]
  plug :id_check when action in [:delete]
  plug :get_root_categories

  def new(conn, _) do
    render(conn, "new.html")
  end

  # If you are using Argon2 or Pbkdf2, add crypto: Comeonin.Argon2
  # or crypto: Comeonin.Pbkdf2 to Login.verify (after Accounts)
  def create(conn, %{"session" => params}) do
    case Login.verify(params, Accounts) do
      {:ok, user} ->
        session_id = Login.gen_session_id("F")
        Accounts.add_session(user, session_id, System.system_time(:second))

        Login.add_session(conn, session_id, user.id)
        |> add_remember_me(user.id, params)
        |> login_success(:request_path)

      {:error, message} ->
        error(conn, message, session_path(conn, :new))
    end
  end

  def delete(%Plug.Conn{assigns: %{current_user: user}} = conn, _) do
    <<session_id::binary-size(17), _::binary>> = get_session(conn, :phauxth_session_id)
    Accounts.delete_session(user, session_id)

    delete_session(conn, :phauxth_session_id)
    |> Phauxth.Remember.delete_rem_cookie()
    |> success("You have been logged out", page_path(conn, :index))
  end

  # This function adds a remember_me cookie to the conn.
  # See the documentation for Phauxth.Remember for more details.
  defp add_remember_me(conn, user_id, %{"remember_me" => "true"}) do
    Phauxth.Remember.add_rem_cookie(conn, user_id)
  end

  defp add_remember_me(conn, _, _), do: conn

  defp get_root_categories(conn, _params) do
    root_cat = Excommerce.Query.Category.get_root_cat(Repo)
    conn
    |> assign(:root_cat, root_cat)
  end
end

lib/excommerce_web/views/session_view.ex
defmodule ExcommerceWeb.SessionView do
  use ExcommerceWeb, :view
end

lib/excommerce_web/templates/session/new.html.eex
<section class="xs-section-padding">
  <div class="container">
    <div class="row">
      <div class="col-md-10 mx-auto">
        <div class="row customer-info-forms">
          <div class="col-md-6">
            <div class="xs-customer-form-wraper">
                <h3>Log in your account</h3>

                <%= form_for @conn, session_path(@conn, :create), [as: :session, class: "xs-customer-form"], fn f -> %>
                  <%= if f.errors != [] do %>
                    <div class="alert alert-danger">
                      <p>Please check the errors below:</p>
                    </div>
                  <% end %>

                  <div class="input-group input-group-append">
                    <%= text_input f, :email, class: "form-control", id: "customer_email", placeholder: "Email Address" %>
                    <i class="icon icon-profile-male input-group-text"></i>
                    <%= error_tag f, :email %>
                  </div>

                  <div class="input-group input-group-append">
                    <%= password_input f, :password, class: "form-control", id: "customer_password", placeholder: "Enter Password" %>
                    <i class="icon icon-key2 input-group-text"></i>
                    <%= error_tag f, :password %>
                  </div>

                  <%= submit "Login", class: "btn btn-primary btn-block" %>
                  <p></p>

                  <div class="custom-control custom-checkbox">
                    <%= checkbox f, :remember_me, class: "custom-control-input", id: "customCheck1" %><label class="custom-control-label"><span>Remember me</span></label>
                  </div>

                    <%= link "Forgot password", to: password_reset_path(@conn, :new), class: "btn btn-danger btn-block" %>
                 <p></p>
                <% end %>

                <span><%= link "Back", to: page_path(@conn, :index), class: "btn btn-primary btn-block" %></span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

lib/excommerce_web/templates/session/script.new.html.eex
    <link rel="stylesheet" href="<%= static_path(@conn, "/assets/css/custom_my_account.css") %>">